name: release assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  bundle:
    strategy:
      matrix:
        os: [ macos-latest, macos-13, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean bundle

      - name: Upload
        env:
          TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.ZUGFERD_RELEASE_KEY }}
        run: |
              for file in $(find build -type f -maxdepth 1)
              do
                echo "RELEASE $file IN $TAG"
                gh release upload $TAG $file
              done
