name: release manually

on: workflow_dispatch

jobs:
  release:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest, macos-13 ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build packageReleaseDistributionForCurrentOS
      - uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ matrix.os }}
          path: build/distributions/main-release/*/*
