name: release manually

on:
  workflow_dispatch:
    inputs:
      macos_arm64:
        description: "Build for MacOS arm64"
        required: true
        default: true
        type: boolean

      macos_x64:
        description: "Build for MacOS x64"
        required: true
        default: true
        type: boolean

      linux_x64:
        description: "Build for Linux x64"
        required: true
        default: true
        type: boolean

      windows_x64:
        description: "Build for Windows x64"
        required: true
        default: true
        type: boolean

jobs:
  release:
    strategy:
      matrix:
        os: [ macos-latest, macos-13, ubuntu-latest, windows-latest ]
        exclude:
          - os: ${{ !github.event.inputs.macos_arm64 && 'macos-latest' }}
          - os: ${{ !github.event.inputs.macos_x64 && 'macos-13' }}
          - os: ${{ !github.event.inputs.linux_x64 && 'ubuntu-latest' }}
          - os: ${{ !github.event.inputs.windows_x64 && 'windows-latest' }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean bundle

      - name: Upload MacOSX-arm64
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          name: MacOSX-arm64
          path: build/*

      - name: Upload MacOSX-x64
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'macos-13' }}
        with:
          name: MacOSX-x64
          path: build/*

      - name: Upload Linux-x64
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: Linux-x64
          path: build/*

      - name: Upload Windows-x64
        uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: Windows-x64
          path: build/*
